version: '3'
services:

  dc:
    build:
      context: ./dc
      dockerfile: Dockerfile
    command: npm start
    restart: always

    # volumes:
    #  - "./dc:/home/support/dc"
    #  - "./dc/node_modules:/home/support/dc/node_modules"
    networks:
     - webapp_network

  lpsm:
    build: ./lpsm
    restart: always

    volumes:
     - "./lpsm:/home/support/lpsm"
    networks:
     - webapp_network

  jobprocessor:
    build:
      context: ./jobprocessor
      dockerfile: Dockerfile
    command: npm start
    restart: always
    networks:
     - webapp_network

  nginx:
    image: "nginx"
    ports:
     - "8000:80"
    volumes:
     - ./reverse_proxy/:/etc/nginx/conf.d
    depends_on:
      - lpsm
      - dc
    networks:
     - webapp_network
networks:
  webapp_network:
    driver: "bridge"

